(define base 10)
(define (square x) (* x x))
(define (offsetSquare x)
  (define base 2)
  (+ (square x) base))
(define result (offsetSquare 4))
(define (fail) (throw "boom"))
(define (main)
  (print result)
  (fail))
